class Error(Exception):
    pass

class ValueNotFound(Error):
    pass